[destination.snowflake.credentials]
database = "dlt_data"
password = "Password"
username = "loader"
host = "ggqwzgy-px17667"
warehouse = "COMPUTE_WH"
role = "DLT_LOADER_ROLE"

[sources.sql_database.credentials]
drivername = "mysql+pymysql" # driver name for the database
database = "chinook" # database name
username = "a" # username associated with the database
host = "localhost" # host address
port = "3306" # port required for connection
