[destination.snowflake.credentials]
database = "dlt_data"
password = "Password"
username = "loader"
host = "ggqwzgy-px17667"
warehouse = "COMPUTE_WH"
role = "DLT_LOADER_ROLE"

[sources.sql_database.credentials]
drivername = "mysql+pymysql" # driver name for the database
database = "chinook" # database name
username = "a" # username associated with the database
password = "******" 
host = "localhost" # host address
port = "3306" # port required for connection

# special setting for PostgreSQL 
[destination.mydb.credentials]
database = "mydb"
username = "a"
password = "******" 
host = "localhost" # or the IP address location of your database
port = 5432
connect_timeout = 15

# For pipeline name dlt_postgre_chinook need to set password
[dlt_postgre_chinook.destination.credentials]
password = "******" 

# Configuration for reading from Mongo DB
[sources.mongodb]
connection_url = "mongodb://root:******@localhost:27017/?authSource=admin" # just connection string
database = "admin"  # Database name (Optional), default database is loaded if not provided.
collection_names = ["customers", "products"]